# Generated by Django 3.2.5 on 2021-08-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Apparel', 'Apparel'), ('Manga', 'Manga'), ('Merchandise', 'Merchandise'), ('Wallpaper', 'Wallpaper')], default='Anime', max_length=50),
        ),
    ]
